### ISSUE TITLE
Week 3: Twitter Client App

### ISSUE THREAD

**Issue by ananavati** [ananavati/codepath_twitter#1]
Assignment submission:
@timothy1ee @nesquena

definitely more polish needed on auto layout constraints
I also wanted to implement these
1. Infinite scroll
2. Retweet, favorite icon states to change based on the retweet status and favorite status, right now I only change the text color of the counts.

**Comment by timothy1ee** [comment]
Good job! The point of this homework was to explore some challenges involved in developing a richer MVC client.
- For buttons with small images, you should still have the button be at least 30x30 or they are hard to tap.
- If you get a chance, you should attempt more of the optional features. They are trickier than they appear and will help prepare you to build richer apps.

Here's my checklist as I'm reviewing the submissions:
- Code styling. The New York Times has a good summary of appropriate Objective-C coding conventions, you should take a quick look [here](https://github.com/NYTimes/objective-c-style-guide).
- Was the current user persisted across restarts?
- Did you create a custom Tweet cell and properly set up Auto Layout constraints?
- Did you augment the User and Tweet model with the required properties?
- Date parsing and formatting is expensive, so consider caching in models when you can.
- Does tapping on a Tweet take you to a detailed Tweet view?
- Is the detailed Tweet view styled like the mock?
- Did you add both standard and retina (@2x) image assets? A new feature of XCode is to use the Images.xcassets, it makes it easier to handle the standard and retina assets. If you only included standard assets, it will be scaled for retina displays which makes them a little blurry.
